<div>
    <!-- People find pleasure in different ways. I find it in keeping my mind clear. - Marcus Aurelius -->
</div>
{{-- resources/views/admin/exams/exports/exams-pdf.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Exams List</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #333;
        }
        .header h2 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background: #4a5568;
            color: white;
            padding: 10px;
            text-align: left;
            font-size: 12px;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background: #f8f9fa;
        }
        .text-center {
            text-align: center;
        }
        .badge-active {
            color: #059669;
            font-weight: bold;
        }
        .badge-inactive {
            color: #dc2626;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Exams List Report</h2>
        <p>Generated on: {{ now()->format('d F Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Class</th>
                <th>Subject</th>
                <th>Exam Date</th>
                <th>Full Marks</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($exams as $i => $exam)
            <tr>
                <td class="text-center">{{ $i+1 }}</td>
                <td>{{ ($exam->classInfo->name ?? '-') . ($exam->classInfo->board->name ? ' (' . $exam->classInfo->board->name . ')' : '') }}</td>
                <td>{{ $exam->subject->name ?? '-' }}</td>
                <td>{{ \Carbon\Carbon::parse($exam->exam_date)->format('d-m-Y') }}</td>
                <td class="text-center">{{ $exam->full_marks }}</td>
                <td>
                    @if($exam->is_active)
                        <span class="badge-active">Active</span>
                    @else
                        <span class="badge-inactive">Inactive</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Total Exams: {{ $exams->count() }} | Generated by {{ auth()->guard('admin')->user()->name ?? 'Admin' }}
    </div>
</body>
</html>