<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title ?? 'Report' }} – Saraswata Academy</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 11px; color: #1a1a2e; margin: 0; padding: 0; }
        .header { background: #2d3461; color: white; padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; }
        .header h1 { margin: 0; font-size: 16px; }
        .header .subheading { font-size: 10px; opacity: .7; }
        .badge-paid { background: #d1fae5; color: #065f46; border-radius: 4px; padding: 2px 8px; font-size: 10px; }
        .badge-due  { background: #fef3c7; color: #92400e; border-radius: 4px; padding: 2px 8px; font-size: 10px; }
        .badge-overdue { background: #fee2e2; color: #991b1b; border-radius: 4px; padding: 2px 8px; font-size: 10px; }
        .filters { font-size: 10px; color: #6b7280; padding: 8px 24px; background: #f8fafc; border-bottom: 1px solid #e5e7eb; }
        table { width: 100%; border-collapse: collapse; margin: 0; }
        thead th { background: #f1f5f9; font-weight: 600; padding: 8px; border-bottom: 2px solid #e2e8f0; text-align: left; }
        tbody td { padding: 7px 8px; border-bottom: 1px solid #f1f5f9; }
        tbody tr:nth-child(even) { background: #f8fafc; }
        .footer { text-align: center; font-size: 9px; color: #9ca3af; padding: 12px; border-top: 1px solid #e5e7eb; margin-top: 8px; }
        .summary-row { background: #dbeafe !important; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="subheading">Saraswata Academy – Management Report</div>
            <h1>{{ $title ?? 'Report' }}</h1>
        </div>
        <div style="text-align:right">
            <div>{{ date('d M Y, H:i') }}</div>
            <div class="subheading">Generated by Admin</div>
        </div>
    </div>

    @if(isset($filterText))
    <div class="filters">Filters: {{ $filterText }}</div>
    @endif

    @yield('pdf-content')

    <div class="footer">Saraswata Academy · Printed on {{ date('d M Y') }} · Confidential</div>
</body>
</html>
