<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #4CAF50;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 11px;
        }
        td {
            padding: 6px;
            border: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .present {
            color: green;
            font-weight: bold;
        }
        .absent {
            color: red;
            font-weight: bold;
        }
        .filters {
            background: #f8f9fa;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Attendance Report</h2>
        <p>Generated on: {{ $generated_at }}</p>
    </div>

    <div class="filters">
        <p><strong>Filters Applied:</strong></p>
        <p>Class: {{ $filters['class_id'] ?? 'All' }}</p>
        <p>Subject: {{ $filters['subject_id'] ?? 'All' }}</p>
        <p>Student: {{ $filters['student_id'] ?? 'All' }}</p>
        <p>Date Range: {{ $filters['from_date'] ?? 'Start' }} to {{ $filters['to_date'] ?? 'End' }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Class</th>
                <th>Subjects</th>
                <th>Student ID</th>
                <th>Student Name</th>
                <th>Roll No</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($attendances as $index => $attendance)
                @php
                    $subjects = $attendance->subjects->pluck('name')->implode(', ');
                @endphp
                
                @if(isset($attendance->student_detail))
                    <!-- Student-specific view -->
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $attendance->attendance_date->format('d-m-Y') }}</td>
                        <td>{{ ($attendance->classInfo->name ?? '-') . ($attendance->classInfo->board->name ? ' (' . $attendance->classInfo->board->name . ')' : '') }}</td>
                        <td>{{ $subjects }}</td>
                        <td>{{ $attendance->student_detail->student->student_id ?? '-' }}</td>
                        <td>{{ $attendance->student_detail->student->name ?? '-' }}</td>
                        <td>{{ $attendance->student_detail->student->roll_no ?? '-' }}</td>
                        <td class="{{ strtolower($attendance->student_detail->status) }}">
                            {{ $attendance->student_detail->status }}
                        </td>
                    </tr>
                @else
                    <!-- Regular view with all students -->
                    @foreach($attendance->details as $detail)
                        <tr>
                            <td>{{ $loop->parent->iteration }}</td>
                            <td>{{ $attendance->attendance_date->format('d-m-Y') }}</td>
                            <td>{{ ($attendance->classInfo->name ?? '-') . ($attendance->classInfo->board->name ? ' (' . $attendance->classInfo->board->name . ')' : '') }}</td>
                            <td>{{ $subjects }}</td>
                            <td>{{ $detail->student->student_id ?? '-' }}</td>
                            <td>{{ $detail->student->name ?? '-' }}</td>
                            <td>{{ $detail->student->roll_no ?? '-' }}</td>
                            <td class="{{ strtolower($detail->status) }}">
                                {{ $detail->status }}
                            </td>
                        </tr>
                    @endforeach
                @endif
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by School Management System</p>
    </div>
</body>
</html>